### ISSUE TITLE
上传的啥也，都不完整

### ISSUE THREAD

**Issue by wty302857194** [rshinich/HapticFeedbackDemo#1]

**Comment by angleyue** [comment]
请问是什么？我上传啥了




| |
于扬
|
|
邮箱：15110061200@163.com
|

签名由 网易邮箱大师 定制

在2020年12月23日 16:58，吴棒棒 写道：

**Comment by rshinich** [comment]
> _No description provided._

你需要什么？哪里不完整了？

**Comment by angleyue** [comment]
我啥也不需要，是我收到这个邮件说“上传的不完整”




| |
于扬
|
|
邮箱：15110061200@163.com
|

签名由 网易邮箱大师 定制

在2020年12月23日 17:04，rshinich 写道：

No description provided.

你需要什么？哪里不完整了？
